name: "🚀 Предложить идею"
description: "Любые идеи для игры, ваша шиза в материю."
title: "[ИДЕЯ]: "
type: Идея
body:
  - type: markdown
    attributes:
      value: |
        ## Называйте заголовок кратко и понятно:
        ### ПРИМЕР: `[ИДЕЯ]: Рыбалка - Добавить новые удочки в карго`
        Это поможет быстрее передать сути проблемы.
        Можно называть и так:
        **`[ИДЕЯ]: Добавить в карго новые удочки`**

  - type: checkboxes
    id: feature_scope
    attributes:
      label: "Что потребует изменений?"
      description: "Выберите типы изменений"
      options:
        - label: "🧱 Код"
        - label: "🎨 Спрайты"
        - label: "🗺 Карты"

  - type: textarea
    id: description
    attributes:
      label: "Описание"
      description: "Опишите идею/фичу"
      placeholder: |
        Добавить в раздел карго набор 'Космический рыбак' с тремя типами удочек (стандартная, глубокая вода, электронная) для ловли разных видов рыб.
        Каждая удочка должна иметь уникальные характеристики: прочность, шанс поимки и специальные возможности.
        Электронная удочка может временно оглушать агрессивную рыбу, но требует батареек.
    validations:
      required: true
